# nginx proxy address - http://172.17.0.1:59000

name: mailu
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

x-env: &default-env
  TZ: ${TZ:-America/New_York}
  SECRET_KEY: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
  SUBNET: ${IPV4_NETWORK:-10.1.1.0/24}
  DOMAIN: ${BASE_DOMAIN_NAME:-example.com}
  HOSTNAMES: ${BASE_HOST_NAME:-$HOSTNAME}
  POSTMASTER: ${APP_ADMIN_USER:-admin}
  INITIAL_ADMIN_ACCOUNT: ${APP_ADMIN_USER:-admin}
  INITIAL_ADMIN_DOMAIN: ${BASE_DOMAIN_NAME:-example.com}
  INITIAL_ADMIN_PW: ${APP_ADMIN_PASS:-changeme_admin_password}
  INITIAL_ADMIN_MODE: ifmissing
  WEB_ADMIN: /admin
  WEB_WEBMAIL: /webmail
  WEBMAIL: snappymail
  WEBDAV: radicale
  WEBSITE: https://${BASE_HOST_NAME:-$HOSTNAME}

services:
  # External dependencies

  # Core services
  front:
    image: ghcr.io/mailu/nginx:latest
    pull_policy: always
    restart: always
    environment:
      TZ: ${TZ:-America/New_York}
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      SECRET_KEY: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      SUBNET: ${IPV4_NETWORK:-10.1.1.0/24}
      DOMAIN: ${BASE_DOMAIN_NAME:-example.com}
      HOSTNAMES: ${BASE_HOST_NAME:-$HOSTNAME}
      POSTMASTER: ${APP_ADMIN_USER:-admin}
      INITIAL_ADMIN_ACCOUNT: ${APP_ADMIN_USER:-admin}
      INITIAL_ADMIN_DOMAIN: ${BASE_DOMAIN_NAME:-example.com}
      INITIAL_ADMIN_PW: ${APP_ADMIN_PASS:-changeme_admin_password}
      INITIAL_ADMIN_MODE: ifmissing
      WEB_ADMIN: /admin
      WEB_WEBMAIL: /webmail
      WEBMAIL: snappymail
      WEBDAV: radicale
      WEBSITE: https://${BASE_HOST_NAME:-$HOSTNAME}
    logging: *default-logging
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '110:110'
      - '995:995'
      - '143:143'
      - '993:993'
      - '4190:4190'
      - '172.17.0.1:59000:443'
    networks:
      - default
      - webmail
      - radicale
      - proxy
      - cloudflare
    volumes:
      - './volumes/data/certs:/certs'
      - './volumes/data/nginx:/overrides:ro'
    depends_on:
      - resolver
    dns:
      - 10.1.1.254
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://front:443'
      - 'cloudflare.hostname=mailu.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.front.entrypoints=http'
      - 'traefik.http.routers.front-secure.tls=true'
      - 'traefik.http.routers.front.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.front-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.front.middlewares=front-https-redirect'
      - 'traefik.http.routers.front-secure.entrypoints=https'
      - 'traefik.http.routers.front-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.front-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.front-secure.service=front'
      - 'traefik.http.services.front.loadbalancer.server.port=443'

  resolver:
    image: ghcr.io/mailu/unbound:latest
    pull_policy: always
    environment: *default-env
    logging: *default-logging
    restart: always
    networks:
      default:
        ipv4_address: 10.1.1.254

  admin:
    image: ghcr.io/mailu/admin:latest
    pull_policy: always
    restart: always
    environment: *default-env
    logging: *default-logging
    volumes:
      - './volumes/data/data:/data'
      - './volumes/data/dkim:/dkim'
    depends_on:
      - redis
      - resolver
    dns:
      - 10.1.1.254

  imap:
    image: ghcr.io/mailu/dovecot:latest
    pull_policy: always
    restart: always
    environment: *default-env
    logging: *default-logging
    volumes:
      - './volumes/data/mail:/mail'
      - './volumes/data/dovecot:/overrides:ro'
    networks:
      - default
      - fts_attachments
    depends_on:
      - front
      - fts_attachments
      - resolver
    dns:
      - 10.1.1.254

  smtp:
    image: ghcr.io/mailu/postfix:latest
    pull_policy: always
    restart: always
    environment: *default-env
    logging: *default-logging
    volumes:
      - './volumes/data/mailqueue:/queue'
      - './volumes/data/postfix:/overrides:ro'
    depends_on:
      - front
      - resolver
    dns:
      - 10.1.1.254

  oletools:
    image: ghcr.io/mailu/oletools:latest
    pull_policy: always
    hostname: oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 10.1.1.254

  fts_attachments:
    image: apache/tika:latest
    pull_policy: always
    hostname: tika
    restart: always
    networks:
      - fts_attachments
    depends_on:
      - resolver
    dns:
      - 10.1.1.254
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -nv -t1 -O /dev/null http://127.0.0.1:9998/tika || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  antispam:
    image: ghcr.io/mailu/rspamd:latest
    pull_policy: always
    hostname: antispam
    restart: always
    environment: *default-env
    logging: *default-logging
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - './volumes/data/rspamd:/overrides:ro'
      - './volumes/data/filter:/var/lib/rspamd'
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 10.1.1.254

  # Optional services
  antivirus:
    image: clamav/clamav:latest
    pull_policy: always
    restart: always
    networks:
      - clamav
    volumes:
      - './volumes/data/filter/clamav:/var/lib/clamav'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webdav:
    image: ghcr.io/mailu/radicale:latest
    pull_policy: always
    restart: always
    volumes:
      - './volumes/data/dav:/data'
    networks:
      - radicale

  fetchmail:
    image: ghcr.io/mailu/fetchmail:latest
    pull_policy: always
    restart: always
    environment: *default-env
    volumes:
      - './volumes/data/fetchmail:/data'
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 10.1.1.254

  # Webmail
  webmail:
    image: ghcr.io/mailu/webmail:latest
    pull_policy: always
    restart: always
    environment: *default-env
    logging: *default-logging
    volumes:
      - './volumes/data/webmail:/data'
      - './volumes/data/snappymail:/overrides:ro'
    networks:
      - webmail
    depends_on:
      - front

  redis:
    image: redis:alpine
    pull_policy: always
    restart: always
    logging: *default-logging
    volumes:
      - './volumes/data/db/redis/mailu:/data'
    depends_on:
      - resolver
    dns:
      - 10.1.1.254

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
        - subnet: fdab:03bb:c928:beef::/64
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  clamav:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
  fts_attachments:
    driver: bridge
    internal: true
  proxy:
    external: true
  cloudflare:
    external: true
